#!/bin/bash
set -eu

MOUNT="$1"
SLEEP="$2"

function errecho {
    >&2 echo "$@"
}

function mounted() {
    if mount | grep -q "$MOUNT"
    then
        echo "true"
    else
        echo "false"
    fi
}

was_mounted="false"
while true;
do
    mnt=$(mounted)
    errecho "MOUNTED: $mnt"
    if [[ "$was_mounted" == false ]] && [[ "$mnt" == true  ]]
    then
        errecho "Detected that $MOUNT is mounted now, running the check"
        res=$(find "$MOUNT" -type f -exec cat {} \; 2>&1 >/dev/null)
        if [[ -z $res ]]
        then
            errecho "No errors detected"
        else
            errecho "Errors detected!"
            errecho "$res"
            errecho "$res" | mail -s "Errors on encfs mount $MOUNT" "$USER"
        fi
    else
        errecho "No change in mount"
    fi
    sleep "$SLEEP"
    was_mounted=$mnt
done
